services:
  frontend:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - innotter-network

  storybook:
    build:
      context: .
      target: development
    command: npm run storybook
    ports:
      - "6006:6006"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - innotter-network

networks:
  innotter-network:
    driver: bridge